// Auto-generated playlist. Re-run generate-playlist.ps1 to refresh.
window.AUTO_PLAYLIST = [
    "Alec Benjamin - Let Me Down Slowly.mp3",
    "Ariana Grande - break up with your girlfriend, i\u0027m bored.mp3",
    "ASKING ALEXANDRIA - The Final Episode.mp3",
    "BAD OMENS - Dethrone.mp3",
    "BAD OMENS - IDWT$.mp3",
    "BAD OMENS - Just Pretend.mp3",
    "BAD OMENS - Like A Villain.mp3",
    "BAD OMENS - Limits.mp3",
    "BAD OMENS - THE DEATH OF PEACE OF MIND.mp3",
    "BAD OMENS - The Grey.mp3",
    "BAD OMENS x POPPY - V.A.N.mp3",
    "BLACK SABBATH - Paranoid.mp3",
    "BLACK VEIL BRIDES - Scarlet Cross.mp3",
    "blackbear - hot girl bummer.mp3",
    "blackbear ft. Gucci Mane - do re mi.mp3",
    "Bon Jovi - You Give Love A Bad Name.mp3",
    "Bring Me The Horizon - Avalanche.mp3",
    "Chase Atlantic - Friends.mp3",
    "Chase Atlantic - Slow Down.mp3",
    "Chase Atlantic - Swim.mp3",
    "Chris Grey - LET THE WORLD BURN.mp3",
    "Chris Grey - WRONG.mp3",
    "Clair Obscur Expedition 33 - Lost Voice.mp3",
    "Clair Obscur_ Expedition 33 - Alicia.mp3",
    "Clair Obscur_ Expedition 33 - Gustave.mp3",
    "Clair Obscur_ Expedition 33 - Lumière.mp3",
    "Cleffy -  Meet you at the Graveyard.mp3",
    "Creepy Nuts - Bling Bang Bang Born.mp3",
    "DIO - Holy Diver.mp3",
    "Falling In Reverse - Popular Monster.mp3",
    "Guns N\u0027 Roses - Sweet Child O\u0027 Mine.mp3",
    "HOLLYWOOD UNDEAD - Everywhere I Go.mp3",
    "Imagine Dragons x J.I.D - Enemy.mp3",
    "Iron Maiden - Blood Brothers.mp3",
    "Iron Maiden - Dance Of Death.mp3",
    "Iron Maiden - Fear of the Dark.mp3",
    "Iron Maiden - For Whom The Bell Tolls.mp3",
    "Iron Maiden - Hallowed Be Thy Name.mp3",
    "Iron Maiden - The Trooper.mp3",
    "IVOXYGEN - Falling.mp3",
    "Joan Jett \u0026 the Blackhearts - I Love Rock \u0027N Roll.mp3",
    "Judas Priest - Painkiller.mp3",
    "Kansas - Carry On Wayward Son.mp3",
    "KAZKA  Плакала.mp3",
    "KISS - I Was Made For Lovin\u0027 You.mp3",
    "Konfuz - Ратата.mp3",
    "Linkin Park - Breaking the Habit.mp3",
    "Linkin Park - CASTLE OF GLASS.mp3",
    "Linkin Park - Faint.mp3",
    "Linkin Park - In The End.mp3",
    "Linkin Park - LOST IN THE ECHO.mp3",
    "Linkin Park - New Divide.mp3",
    "Linkin Park - Numb.mp3",
    "Linkin Park - Somewhere I Belong.mp3",
    "Linkin Park- Leave Out All The Rest.mp3",
    "Linkin Park What I\u0027ve Done.mp3",
    "Living Life, In The Night.mp3",
    "Lord Huron - The Night We Met.mp3",
    "Mama I\u0027m a criminal.mp3",
    "Marina and The Diamonds - Bubblegum Bitch.mp3",
    "Megadeth - Holy Wars...The Punishment Due.mp3",
    "Metallica - Enter Sandman.mp3",
    "Metallica - Fade To Black.mp3",
    "Metallica - Nothing Else Matters.mp3",
    "Metallica - Seek \u0026 Destroy.mp3",
    "Metallica - The Unforgiven.mp3",
    "Miracle Of Sound ft. Peyton Parrish - VALHALLA CALLING.mp3",
    "Motionless In White - Another Life.mp3",
    "Motörhead  Ace Of Spades.mp3",
    "My Demons - Starset.mp3",
    "NEFFEX - Grateful.mp3",
    "Night Lovell - Polozhenie.mp3",
    "Night Lovell - Still Cold (ft. Moji).mp3",
    "Nightcore - Hometown Smile.mp3",
    "Nightcore - Symphony.mp3",
    "Nirvana - Smells Like Teen Spirit.mp3",
    "No Doubt - Don\u0027t Speak.mp3",
    "Ozzy Osbourne - Crazy Train.mp3",
    "OZZY OSBOURNE - Mama, I\u0027m Coming Home.mp3",
    "Paramore - Decode.mp3",
    "Post Malone, Swae Lee - Sunflower.mp3",
    "Powfu ft. beabadoobee - death bed.mp3",
    "Rauf \u0026 Faik -  это ли счастье.mp3",
    "Rauf \u0026 Faik - вечера.mp3",
    "Rauf \u0026 Faik - детство.mp3",
    "Rauf \u0026 Faik - колыбельная.mp3",
    "Rauf \u0026 Faik - мама.mp3",
    "Rauf \u0026 Faik - я люблю тебя давно.mp3",
    "Reed Wonder, Aurora Olivas - The Machine.mp3",
    "Sershen\u0026Zaritskaya - Back in Black.mp3",
    "Shaka Ponk - I\u0027m Picky.mp3",
    "Sleep Token - Alkaline.mp3",
    "Sleep Token - Aqua Regia.mp3",
    "Sleep Token - Ascensionism.mp3",
    "Sleep Token - Give.mp3",
    "Sleep Token - Provider.mp3",
    "Sleep Token - Take Me Back To Eden.mp3",
    "Sleep Token - The Summoning.mp3",
    "Slipknot - Psychosocial.mp3",
    "Starset - Monster.mp3",
    "Stromae \u0026 Pomme - Ma Meilleure Ennemie.mp3",
    "System Of A Down - Chop Suey.mp3",
    "System Of A Down - Toxicity.mp3",
    "The Cranberries - Zombie.mp3",
    "The Offspring - The Kids Aren\u0027t Alright.mp3",
    "This is our world.mp3",
    "Three Days Grace - I Hate Everything About You.mp3",
    "Three Days Grace - Never Too Late.mp3",
    "Une vie à t\u0027aimer.mp3",
    "W.A.S.P. - Wild Child.mp3",
    "Waste.mp3",
    "Бабек Мамедрзаев - Принцесса.mp3"
    "hello.mp3"
];
